UPDATE

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,36 +1,47 @@
 name: Java CI
 
-on: [push, pull_request]
+on:
+  push:
+    branches:
+      - main
+  pull_request:
+    branches:
+      - main
 
 jobs:
   build:
     runs-on: ubuntu-latest
-
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+      - uses: actions/checkout@v2
 
-      - name: Set up JDK
-        uses: actions/setup-java@v3
+      - name: Set up JDK 17
+        uses: actions/setup-java@v2
         with:
+          java-version: '17'
           distribution: 'temurin'
-          java-version: '20'
 
-      - name: Build the project
-        uses: gradle/gradle-build-action@v2
-        with:
-          arguments: build
-          build-root-directory: app
+      - name: Build with Gradle
+        run: ./gradlew build
 
-      - name: Run tests and generate JaCoCo report
-        run: ./app/gradlew -p app test jacocoTestReport
+      - name: Run tests and generate coverage report
+        run: ./gradlew test jacocoTestReport
+
+      - name: List coverage report directory
+        run: ls -la app/build/reports/jacoco/test
+
+      - name: Check coverage report file
+        run: |
+          if [ ! -f app/build/reports/jacoco/test/jacocoTestReport.xml ]; then
+            echo "Coverage report not found!"
+            exit 1
+          fi
 
       - name: Publish code coverage to Code Climate
         uses: paambaati/codeclimate-action@v3.0.0
         env:
           CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
         with:
-          coverageCommand: ./app/gradlew -p app jacocoTestReport
-          coverageLocations: ${{ github.workspace }}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
+          coverageCommand: ./gradlew jacocoTestReport
+          coverageLocations: ${{ github.workspace }}/app/build/reports/jacoco/test/jacocoTestReport.xml
           prefix: app/src/main/java
           debug: true
